//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace HClient.Data
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class DBEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“DBEntities”部分中的连接字符串初始化新 DBEntities 对象。
        /// </summary>
        public DBEntities() : base("name=DBEntities", "DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 DBEntities 对象。
        /// </summary>
        public DBEntities(string connectionString) : base(connectionString, "DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 DBEntities 对象。
        /// </summary>
        public DBEntities(EntityConnection connection) : base(connection, "DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<CONFIG> CONFIG
        {
            get
            {
                if ((_CONFIG == null))
                {
                    _CONFIG = base.CreateObjectSet<CONFIG>("CONFIG");
                }
                return _CONFIG;
            }
        }
        private ObjectSet<CONFIG> _CONFIG;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<COOKIE> COOKIE
        {
            get
            {
                if ((_COOKIE == null))
                {
                    _COOKIE = base.CreateObjectSet<COOKIE>("COOKIE");
                }
                return _COOKIE;
            }
        }
        private ObjectSet<COOKIE> _COOKIE;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<GROUP> GROUP
        {
            get
            {
                if ((_GROUP == null))
                {
                    _GROUP = base.CreateObjectSet<GROUP>("GROUP");
                }
                return _GROUP;
            }
        }
        private ObjectSet<GROUP> _GROUP;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<IMG> IMG
        {
            get
            {
                if ((_IMG == null))
                {
                    _IMG = base.CreateObjectSet<IMG>("IMG");
                }
                return _IMG;
            }
        }
        private ObjectSet<IMG> _IMG;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<PO> PO
        {
            get
            {
                if ((_PO == null))
                {
                    _PO = base.CreateObjectSet<PO>("PO");
                }
                return _PO;
            }
        }
        private ObjectSet<PO> _PO;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<POST> POST
        {
            get
            {
                if ((_POST == null))
                {
                    _POST = base.CreateObjectSet<POST>("POST");
                }
                return _POST;
            }
        }
        private ObjectSet<POST> _POST;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<THREAD> THREAD
        {
            get
            {
                if ((_THREAD == null))
                {
                    _THREAD = base.CreateObjectSet<THREAD>("THREAD");
                }
                return _THREAD;
            }
        }
        private ObjectSet<THREAD> _THREAD;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 CONFIG EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToCONFIG(CONFIG cONFIG)
        {
            base.AddObject("CONFIG", cONFIG);
        }
    
        /// <summary>
        /// 用于向 COOKIE EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToCOOKIE(COOKIE cOOKIE)
        {
            base.AddObject("COOKIE", cOOKIE);
        }
    
        /// <summary>
        /// 用于向 GROUP EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToGROUP(GROUP gROUP)
        {
            base.AddObject("GROUP", gROUP);
        }
    
        /// <summary>
        /// 用于向 IMG EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToIMG(IMG iMG)
        {
            base.AddObject("IMG", iMG);
        }
    
        /// <summary>
        /// 用于向 PO EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPO(PO pO)
        {
            base.AddObject("PO", pO);
        }
    
        /// <summary>
        /// 用于向 POST EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPOST(POST pOST)
        {
            base.AddObject("POST", pOST);
        }
    
        /// <summary>
        /// 用于向 THREAD EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTHREAD(THREAD tHREAD)
        {
            base.AddObject("THREAD", tHREAD);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBModel", Name="CONFIG")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CONFIG : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 CONFIG 对象。
        /// </summary>
        /// <param name="cONFIG_NAME">CONFIG_NAME 属性的初始值。</param>
        /// <param name="cONFIG_ID">CONFIG_ID 属性的初始值。</param>
        public static CONFIG CreateCONFIG(global::System.String cONFIG_NAME, global::System.Guid cONFIG_ID)
        {
            CONFIG cONFIG = new CONFIG();
            cONFIG.CONFIG_NAME = cONFIG_NAME;
            cONFIG.CONFIG_ID = cONFIG_ID;
            return cONFIG;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CONFIG_NAME
        {
            get
            {
                return _CONFIG_NAME;
            }
            set
            {
                OnCONFIG_NAMEChanging(value);
                ReportPropertyChanging("CONFIG_NAME");
                _CONFIG_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CONFIG_NAME");
                OnCONFIG_NAMEChanged();
            }
        }
        private global::System.String _CONFIG_NAME;
        partial void OnCONFIG_NAMEChanging(global::System.String value);
        partial void OnCONFIG_NAMEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CONFIG_ID
        {
            get
            {
                return _CONFIG_ID;
            }
            set
            {
                if (_CONFIG_ID != value)
                {
                    OnCONFIG_IDChanging(value);
                    ReportPropertyChanging("CONFIG_ID");
                    _CONFIG_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CONFIG_ID");
                    OnCONFIG_IDChanged();
                }
            }
        }
        private global::System.Guid _CONFIG_ID;
        partial void OnCONFIG_IDChanging(global::System.Guid value);
        partial void OnCONFIG_IDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBModel", Name="COOKIE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class COOKIE : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 COOKIE 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static COOKIE CreateCOOKIE(global::System.Guid id)
        {
            COOKIE cOOKIE = new COOKIE();
            cOOKIE.ID = id;
            return cOOKIE;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USERID
        {
            get
            {
                return _USERID;
            }
            set
            {
                OnUSERIDChanging(value);
                ReportPropertyChanging("USERID");
                _USERID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USERID");
                OnUSERIDChanged();
            }
        }
        private global::System.String _USERID;
        partial void OnUSERIDChanging(global::System.String value);
        partial void OnUSERIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SAILSID
        {
            get
            {
                return _SAILSID;
            }
            set
            {
                OnSAILSIDChanging(value);
                ReportPropertyChanging("SAILSID");
                _SAILSID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SAILSID");
                OnSAILSIDChanged();
            }
        }
        private global::System.String _SAILSID;
        partial void OnSAILSIDChanging(global::System.String value);
        partial void OnSAILSIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TC
        {
            get
            {
                return _TC;
            }
            set
            {
                OnTCChanging(value);
                ReportPropertyChanging("TC");
                _TC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TC");
                OnTCChanged();
            }
        }
        private global::System.String _TC;
        partial void OnTCChanging(global::System.String value);
        partial void OnTCChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] DB
        {
            get
            {
                return StructuralObject.GetValidValue(_DB);
            }
            set
            {
                OnDBChanging(value);
                ReportPropertyChanging("DB");
                _DB = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DB");
                OnDBChanged();
            }
        }
        private global::System.Byte[] _DB;
        partial void OnDBChanging(global::System.Byte[] value);
        partial void OnDBChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NO
        {
            get
            {
                return _NO;
            }
            set
            {
                OnNOChanging(value);
                ReportPropertyChanging("NO");
                _NO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NO");
                OnNOChanged();
            }
        }
        private global::System.String _NO;
        partial void OnNOChanging(global::System.String value);
        partial void OnNOChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBModel", Name="GROUP")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GROUP : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 GROUP 对象。
        /// </summary>
        /// <param name="gROUP_ID">GROUP_ID 属性的初始值。</param>
        /// <param name="gROUP_TITLE">GROUP_TITLE 属性的初始值。</param>
        public static GROUP CreateGROUP(global::System.Guid gROUP_ID, global::System.String gROUP_TITLE)
        {
            GROUP gROUP = new GROUP();
            gROUP.GROUP_ID = gROUP_ID;
            gROUP.GROUP_TITLE = gROUP_TITLE;
            return gROUP;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid GROUP_ID
        {
            get
            {
                return _GROUP_ID;
            }
            set
            {
                if (_GROUP_ID != value)
                {
                    OnGROUP_IDChanging(value);
                    ReportPropertyChanging("GROUP_ID");
                    _GROUP_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GROUP_ID");
                    OnGROUP_IDChanged();
                }
            }
        }
        private global::System.Guid _GROUP_ID;
        partial void OnGROUP_IDChanging(global::System.Guid value);
        partial void OnGROUP_IDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GROUP_TITLE
        {
            get
            {
                return _GROUP_TITLE;
            }
            set
            {
                OnGROUP_TITLEChanging(value);
                ReportPropertyChanging("GROUP_TITLE");
                _GROUP_TITLE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GROUP_TITLE");
                OnGROUP_TITLEChanged();
            }
        }
        private global::System.String _GROUP_TITLE;
        partial void OnGROUP_TITLEChanging(global::System.String value);
        partial void OnGROUP_TITLEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GROUP_IMG
        {
            get
            {
                return _GROUP_IMG;
            }
            set
            {
                OnGROUP_IMGChanging(value);
                ReportPropertyChanging("GROUP_IMG");
                _GROUP_IMG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GROUP_IMG");
                OnGROUP_IMGChanged();
            }
        }
        private global::System.String _GROUP_IMG;
        partial void OnGROUP_IMGChanging(global::System.String value);
        partial void OnGROUP_IMGChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> GROUP_NO
        {
            get
            {
                return _GROUP_NO;
            }
            set
            {
                OnGROUP_NOChanging(value);
                ReportPropertyChanging("GROUP_NO");
                _GROUP_NO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GROUP_NO");
                OnGROUP_NOChanged();
            }
        }
        private Nullable<global::System.Int64> _GROUP_NO;
        partial void OnGROUP_NOChanging(Nullable<global::System.Int64> value);
        partial void OnGROUP_NOChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GROUP_META
        {
            get
            {
                return _GROUP_META;
            }
            set
            {
                OnGROUP_METAChanging(value);
                ReportPropertyChanging("GROUP_META");
                _GROUP_META = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GROUP_META");
                OnGROUP_METAChanged();
            }
        }
        private global::System.String _GROUP_META;
        partial void OnGROUP_METAChanging(global::System.String value);
        partial void OnGROUP_METAChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBModel", Name="IMG")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class IMG : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 IMG 对象。
        /// </summary>
        /// <param name="iMG_ID">IMG_ID 属性的初始值。</param>
        public static IMG CreateIMG(global::System.Guid iMG_ID)
        {
            IMG iMG = new IMG();
            iMG.IMG_ID = iMG_ID;
            return iMG;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid IMG_ID
        {
            get
            {
                return _IMG_ID;
            }
            set
            {
                if (_IMG_ID != value)
                {
                    OnIMG_IDChanging(value);
                    ReportPropertyChanging("IMG_ID");
                    _IMG_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IMG_ID");
                    OnIMG_IDChanged();
                }
            }
        }
        private global::System.Guid _IMG_ID;
        partial void OnIMG_IDChanging(global::System.Guid value);
        partial void OnIMG_IDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IMG_DIR
        {
            get
            {
                return _IMG_DIR;
            }
            set
            {
                OnIMG_DIRChanging(value);
                ReportPropertyChanging("IMG_DIR");
                _IMG_DIR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IMG_DIR");
                OnIMG_DIRChanged();
            }
        }
        private global::System.String _IMG_DIR;
        partial void OnIMG_DIRChanging(global::System.String value);
        partial void OnIMG_DIRChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IMG_TYPE
        {
            get
            {
                return _IMG_TYPE;
            }
            set
            {
                OnIMG_TYPEChanging(value);
                ReportPropertyChanging("IMG_TYPE");
                _IMG_TYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IMG_TYPE");
                OnIMG_TYPEChanged();
            }
        }
        private global::System.String _IMG_TYPE;
        partial void OnIMG_TYPEChanging(global::System.String value);
        partial void OnIMG_TYPEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> IMG_ISTHUMB
        {
            get
            {
                return _IMG_ISTHUMB;
            }
            set
            {
                OnIMG_ISTHUMBChanging(value);
                ReportPropertyChanging("IMG_ISTHUMB");
                _IMG_ISTHUMB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IMG_ISTHUMB");
                OnIMG_ISTHUMBChanged();
            }
        }
        private Nullable<global::System.Int64> _IMG_ISTHUMB;
        partial void OnIMG_ISTHUMBChanging(Nullable<global::System.Int64> value);
        partial void OnIMG_ISTHUMBChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBModel", Name="PO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PO : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 PO 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static PO CreatePO(global::System.Guid id)
        {
            PO pO = new PO();
            pO.ID = id;
            return pO;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ISBAN
        {
            get
            {
                return _ISBAN;
            }
            set
            {
                OnISBANChanging(value);
                ReportPropertyChanging("ISBAN");
                _ISBAN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ISBAN");
                OnISBANChanged();
            }
        }
        private global::System.String _ISBAN;
        partial void OnISBANChanging(global::System.String value);
        partial void OnISBANChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USED_ID
        {
            get
            {
                return _USED_ID;
            }
            set
            {
                OnUSED_IDChanging(value);
                ReportPropertyChanging("USED_ID");
                _USED_ID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USED_ID");
                OnUSED_IDChanged();
            }
        }
        private global::System.String _USED_ID;
        partial void OnUSED_IDChanging(global::System.String value);
        partial void OnUSED_IDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBModel", Name="POST")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class POST : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 POST 对象。
        /// </summary>
        /// <param name="pOST_ID">POST_ID 属性的初始值。</param>
        /// <param name="pOID">POID 属性的初始值。</param>
        public static POST CreatePOST(global::System.Guid pOST_ID, global::System.String pOID)
        {
            POST pOST = new POST();
            pOST.POST_ID = pOST_ID;
            pOST.POID = pOID;
            return pOST;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid POST_ID
        {
            get
            {
                return _POST_ID;
            }
            set
            {
                if (_POST_ID != value)
                {
                    OnPOST_IDChanging(value);
                    ReportPropertyChanging("POST_ID");
                    _POST_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("POST_ID");
                    OnPOST_IDChanged();
                }
            }
        }
        private global::System.Guid _POST_ID;
        partial void OnPOST_IDChanging(global::System.Guid value);
        partial void OnPOST_IDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String POST_TITLE
        {
            get
            {
                return _POST_TITLE;
            }
            set
            {
                OnPOST_TITLEChanging(value);
                ReportPropertyChanging("POST_TITLE");
                _POST_TITLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("POST_TITLE");
                OnPOST_TITLEChanged();
            }
        }
        private global::System.String _POST_TITLE;
        partial void OnPOST_TITLEChanging(global::System.String value);
        partial void OnPOST_TITLEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String POST_EMAIL
        {
            get
            {
                return _POST_EMAIL;
            }
            set
            {
                OnPOST_EMAILChanging(value);
                ReportPropertyChanging("POST_EMAIL");
                _POST_EMAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("POST_EMAIL");
                OnPOST_EMAILChanged();
            }
        }
        private global::System.String _POST_EMAIL;
        partial void OnPOST_EMAILChanging(global::System.String value);
        partial void OnPOST_EMAILChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String POST_TIME
        {
            get
            {
                return _POST_TIME;
            }
            set
            {
                OnPOST_TIMEChanging(value);
                ReportPropertyChanging("POST_TIME");
                _POST_TIME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("POST_TIME");
                OnPOST_TIMEChanged();
            }
        }
        private global::System.String _POST_TIME;
        partial void OnPOST_TIMEChanging(global::System.String value);
        partial void OnPOST_TIMEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String POST_NAME
        {
            get
            {
                return _POST_NAME;
            }
            set
            {
                OnPOST_NAMEChanging(value);
                ReportPropertyChanging("POST_NAME");
                _POST_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("POST_NAME");
                OnPOST_NAMEChanged();
            }
        }
        private global::System.String _POST_NAME;
        partial void OnPOST_NAMEChanging(global::System.String value);
        partial void OnPOST_NAMEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String POST_IMG
        {
            get
            {
                return _POST_IMG;
            }
            set
            {
                OnPOST_IMGChanging(value);
                ReportPropertyChanging("POST_IMG");
                _POST_IMG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("POST_IMG");
                OnPOST_IMGChanged();
            }
        }
        private global::System.String _POST_IMG;
        partial void OnPOST_IMGChanging(global::System.String value);
        partial void OnPOST_IMGChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String POST_CONTENT
        {
            get
            {
                return _POST_CONTENT;
            }
            set
            {
                OnPOST_CONTENTChanging(value);
                ReportPropertyChanging("POST_CONTENT");
                _POST_CONTENT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("POST_CONTENT");
                OnPOST_CONTENTChanged();
            }
        }
        private global::System.String _POST_CONTENT;
        partial void OnPOST_CONTENTChanging(global::System.String value);
        partial void OnPOST_CONTENTChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String THREAD_ID
        {
            get
            {
                return _THREAD_ID;
            }
            set
            {
                OnTHREAD_IDChanging(value);
                ReportPropertyChanging("THREAD_ID");
                _THREAD_ID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("THREAD_ID");
                OnTHREAD_IDChanged();
            }
        }
        private global::System.String _THREAD_ID;
        partial void OnTHREAD_IDChanging(global::System.String value);
        partial void OnTHREAD_IDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String POID
        {
            get
            {
                return _POID;
            }
            set
            {
                OnPOIDChanging(value);
                ReportPropertyChanging("POID");
                _POID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("POID");
                OnPOIDChanged();
            }
        }
        private global::System.String _POID;
        partial void OnPOIDChanging(global::System.String value);
        partial void OnPOIDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBModel", Name="THREAD")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class THREAD : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 THREAD 对象。
        /// </summary>
        /// <param name="tHREAD_ID">THREAD_ID 属性的初始值。</param>
        /// <param name="gROUP_ID">GROUP_ID 属性的初始值。</param>
        /// <param name="pOID">POID 属性的初始值。</param>
        public static THREAD CreateTHREAD(global::System.Guid tHREAD_ID, global::System.String gROUP_ID, global::System.String pOID)
        {
            THREAD tHREAD = new THREAD();
            tHREAD.THREAD_ID = tHREAD_ID;
            tHREAD.GROUP_ID = gROUP_ID;
            tHREAD.POID = pOID;
            return tHREAD;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid THREAD_ID
        {
            get
            {
                return _THREAD_ID;
            }
            set
            {
                if (_THREAD_ID != value)
                {
                    OnTHREAD_IDChanging(value);
                    ReportPropertyChanging("THREAD_ID");
                    _THREAD_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("THREAD_ID");
                    OnTHREAD_IDChanged();
                }
            }
        }
        private global::System.Guid _THREAD_ID;
        partial void OnTHREAD_IDChanging(global::System.Guid value);
        partial void OnTHREAD_IDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String THREAD_TITLE
        {
            get
            {
                return _THREAD_TITLE;
            }
            set
            {
                OnTHREAD_TITLEChanging(value);
                ReportPropertyChanging("THREAD_TITLE");
                _THREAD_TITLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("THREAD_TITLE");
                OnTHREAD_TITLEChanged();
            }
        }
        private global::System.String _THREAD_TITLE;
        partial void OnTHREAD_TITLEChanging(global::System.String value);
        partial void OnTHREAD_TITLEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String THREAD_EMAIL
        {
            get
            {
                return _THREAD_EMAIL;
            }
            set
            {
                OnTHREAD_EMAILChanging(value);
                ReportPropertyChanging("THREAD_EMAIL");
                _THREAD_EMAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("THREAD_EMAIL");
                OnTHREAD_EMAILChanged();
            }
        }
        private global::System.String _THREAD_EMAIL;
        partial void OnTHREAD_EMAILChanging(global::System.String value);
        partial void OnTHREAD_EMAILChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String THREAD_TIME
        {
            get
            {
                return _THREAD_TIME;
            }
            set
            {
                OnTHREAD_TIMEChanging(value);
                ReportPropertyChanging("THREAD_TIME");
                _THREAD_TIME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("THREAD_TIME");
                OnTHREAD_TIMEChanged();
            }
        }
        private global::System.String _THREAD_TIME;
        partial void OnTHREAD_TIMEChanging(global::System.String value);
        partial void OnTHREAD_TIMEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String THREAD_IMG
        {
            get
            {
                return _THREAD_IMG;
            }
            set
            {
                OnTHREAD_IMGChanging(value);
                ReportPropertyChanging("THREAD_IMG");
                _THREAD_IMG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("THREAD_IMG");
                OnTHREAD_IMGChanged();
            }
        }
        private global::System.String _THREAD_IMG;
        partial void OnTHREAD_IMGChanging(global::System.String value);
        partial void OnTHREAD_IMGChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String THREAD_NAME
        {
            get
            {
                return _THREAD_NAME;
            }
            set
            {
                OnTHREAD_NAMEChanging(value);
                ReportPropertyChanging("THREAD_NAME");
                _THREAD_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("THREAD_NAME");
                OnTHREAD_NAMEChanged();
            }
        }
        private global::System.String _THREAD_NAME;
        partial void OnTHREAD_NAMEChanging(global::System.String value);
        partial void OnTHREAD_NAMEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> THREAD_ISVISIBLE
        {
            get
            {
                return _THREAD_ISVISIBLE;
            }
            set
            {
                OnTHREAD_ISVISIBLEChanging(value);
                ReportPropertyChanging("THREAD_ISVISIBLE");
                _THREAD_ISVISIBLE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("THREAD_ISVISIBLE");
                OnTHREAD_ISVISIBLEChanged();
            }
        }
        private Nullable<global::System.Int64> _THREAD_ISVISIBLE;
        partial void OnTHREAD_ISVISIBLEChanging(Nullable<global::System.Int64> value);
        partial void OnTHREAD_ISVISIBLEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> THREAD_ISSAGE
        {
            get
            {
                return _THREAD_ISSAGE;
            }
            set
            {
                OnTHREAD_ISSAGEChanging(value);
                ReportPropertyChanging("THREAD_ISSAGE");
                _THREAD_ISSAGE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("THREAD_ISSAGE");
                OnTHREAD_ISSAGEChanged();
            }
        }
        private Nullable<global::System.Int64> _THREAD_ISSAGE;
        partial void OnTHREAD_ISSAGEChanging(Nullable<global::System.Int64> value);
        partial void OnTHREAD_ISSAGEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> THREAD_ISFOCUS
        {
            get
            {
                return _THREAD_ISFOCUS;
            }
            set
            {
                OnTHREAD_ISFOCUSChanging(value);
                ReportPropertyChanging("THREAD_ISFOCUS");
                _THREAD_ISFOCUS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("THREAD_ISFOCUS");
                OnTHREAD_ISFOCUSChanged();
            }
        }
        private Nullable<global::System.Int64> _THREAD_ISFOCUS;
        partial void OnTHREAD_ISFOCUSChanging(Nullable<global::System.Int64> value);
        partial void OnTHREAD_ISFOCUSChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> THREAD_ISDAILY
        {
            get
            {
                return _THREAD_ISDAILY;
            }
            set
            {
                OnTHREAD_ISDAILYChanging(value);
                ReportPropertyChanging("THREAD_ISDAILY");
                _THREAD_ISDAILY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("THREAD_ISDAILY");
                OnTHREAD_ISDAILYChanged();
            }
        }
        private Nullable<global::System.Int64> _THREAD_ISDAILY;
        partial void OnTHREAD_ISDAILYChanging(Nullable<global::System.Int64> value);
        partial void OnTHREAD_ISDAILYChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GROUP_ID
        {
            get
            {
                return _GROUP_ID;
            }
            set
            {
                OnGROUP_IDChanging(value);
                ReportPropertyChanging("GROUP_ID");
                _GROUP_ID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GROUP_ID");
                OnGROUP_IDChanged();
            }
        }
        private global::System.String _GROUP_ID;
        partial void OnGROUP_IDChanging(global::System.String value);
        partial void OnGROUP_IDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String THREAD_CONTENT
        {
            get
            {
                return _THREAD_CONTENT;
            }
            set
            {
                OnTHREAD_CONTENTChanging(value);
                ReportPropertyChanging("THREAD_CONTENT");
                _THREAD_CONTENT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("THREAD_CONTENT");
                OnTHREAD_CONTENTChanged();
            }
        }
        private global::System.String _THREAD_CONTENT;
        partial void OnTHREAD_CONTENTChanging(global::System.String value);
        partial void OnTHREAD_CONTENTChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String POID
        {
            get
            {
                return _POID;
            }
            set
            {
                OnPOIDChanging(value);
                ReportPropertyChanging("POID");
                _POID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("POID");
                OnPOIDChanged();
            }
        }
        private global::System.String _POID;
        partial void OnPOIDChanging(global::System.String value);
        partial void OnPOIDChanged();

        #endregion

    
    }

    #endregion

    
}
